# Generated by Django 5.1.6 on 2025-03-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodDistribution', '0005_remove_profile_id_user_alter_profile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
