# Generated by Django 5.1.6 on 2025-03-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDistribution', '0011_alter_profile_options_alter_profile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('volunteer', 'Volunteer'), ('beneficiary', 'Beneficiary'), ('donor', 'Donor')], default='beneficiary', max_length=20),
        ),
    ]
