# Generated by Django 5.1.7 on 2025-04-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDistribution', '0013_alter_volunteerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodstock',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='foodstock',
            name='storage_location',
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('grains', 'Grains'), ('canned', 'Canned'), ('dried', 'Dried'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('frozen', 'Frozen'), ('baked', 'Baked'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('spices', 'Spices')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodstock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
