# Generated by Django 5.1.7 on 2025-04-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDistribution', '0015_remove_food_id_remove_foodstock_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodstock',
            name='food_type',
            field=models.CharField(choices=[('grains', 'Grains'), ('canned', 'Canned'), ('dried', 'Dried'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('frozen', 'Frozen'), ('baked', 'Baked'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('spices', 'Spices')], default='', max_length=100),
        ),
    ]
