# Generated by Django 5.1.6 on 2025-04-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDistribution', '0018_alter_food_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monetarydonation',
            name='id',
        ),
        migrations.AddField(
            model_name='monetarydonation',
            name='MonetaryDonation_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
