# Generated by Django 5.2 on 2025-05-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDistribution', '0019_remove_monetarydonation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='monetarydonation',
            name='MonetaryDonation_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
