# Generated by Django 5.2 on 2025-05-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDistribution', '0019_remove_monetarydonation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='region',
            field=models.CharField(choices=[('adamawa', 'Adamawa'), ('centre', 'Centre'), ('east', 'East'), ('far_north', 'Far North'), ('littoral', 'Littoral'), ('north', 'North'), ('south', 'South'), ('south_west', 'South-West'), ('west', 'West'), ('north_west', 'North-West')], default='littoral', max_length=50),
        ),
        migrations.AlterField(
            model_name='monetarydonation',
            name='MonetaryDonation_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
