# Generated by Django 5.2 on 2025-05-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodDistribution', '0020_beneficiaryprofile_region_and_more'),
        ('foodDistribution', '0020_volunteerprofile_isavailable_and_more'),
    ]

    operations = [
    ]
