# Generated by Django 5.2 on 2025-05-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodDistribution', '0021_merge_20250506_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionplan',
            name='assigned_volunteers',
        ),
    ]
