# Generated by Django 5.2 on 2025-05-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodDistribution', '0022_remove_distributionplan_assigned_volunteers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistributionPlan',
        ),
    ]
