# Generated by Django 5.2 on 2025-05-06 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDistribution', '0023_delete_distributionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=255)),
                ('end_point', models.CharField(max_length=255)),
                ('route_details', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateTimeField()),
                ('plan_status', models.CharField(default='planned', max_length=20)),
                ('assigned_volunteers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='foodDistribution.volunteerprofile')),
            ],
        ),
    ]
